### ISSUE TITLE
cut talk takes rather long

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#17]
I set a start and end point.

6 minutes and counting, but talk still in cut_pending state... That is (much) longer than expected...

**Comment by yoe** [comment]
not a bug, just took rather long because we're faking things a bit and the system believed the end time of the raw file was before the start time, and I had to fix that up manually.

This will break every hour again as long as the `detect_files` script runs from cron fwiw, but that's okay as long as we're only testing.
