### ISSUE TITLE
limit review rights to track instead of room

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#22]
A devroom manager is responsible for a track/devroom, not a physical room. A good example is the python devroom that extends across two days in two different physical rooms.

Limiting a user's review access should happen to one or more tracks instead of one room (if at all). No access limitations might benefit from a combination with reviewer credits on the pre- or postroll. "Who messed up this review? Ah, Joske Vermeulen!"...

**Comment by yoe** [comment]
Been thinking about this a bit more.

Track managers get Cc'd on the notification emails that get sent to speakers. This allows them to do the reviews with the same workflow as the speakers themselves.

Since the admin page allows a reviewer to make more mistakes than the nonce pages, I don't want to give too many people access to that UI without explaining things first. OTOH, changing things so that per-track admins don't have the ability to make too many mistakes would require more work than I have time for

Next year, perhaps.

**Comment by yoe** [comment]
having track managers see the nonce urls allows them to do all the review that they need to do. I don't think we need to move on with this, so closing.
