### ISSUE TITLE
preroll and postroll

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#3]
See https://github.com/FOSDEM/video/blob/master/software/processdump/split_video.py#L85-L103 for a working prototype using ffmpeg.

**Comment by yoe** [comment]
I was actually planning on copying what veyepar does in this area:

- Take an SVG template with specific markers (e.g., "@SPEAKERS@", "@TITLE@", etc)
- Run regexes over the SVG template (think "sed", except perl) to replace those markers with data for the talk
- Run inkscape with a command-line option to export PNG files
- Use the PNG files as an asset to build a film

The advantage of this is that many graphics designers know inkscape (or at least a tool that can output SVG files), which makes it easy for us to talk to them.

**Comment by markvdb** [comment]
Inkscape? It's a good idea to keep dependencies minimal...

**Comment by yoe** [comment]
Disagree. The advantage of being able to run `inkscape --export-png=foo.png` (which doesn't need an X server!) rather than having to redo an SVG with bare ffmpeg calls far far far outweighs any disadvantages that the dependency chain of inkscape might add.

Also, note that installing inkscape only needs to be done on the host where transcoding will be run, not on the stream backend servers.

**Comment by yoe** [comment]
This is now implemented.
