### ISSUE TITLE
What should I do if the approved video has an issue?

### ISSUE THREAD

**Issue by kasbah** [yoe/sreview#33]
Really loving this web service and the speed at which the videos are appearing. Thanks so much! 

I just noticed in the [video I approved](https://fosdem.org/2017/schedule/event/kitnic_it/) my voice is mostly on the left side. Anything I can do at this point?

**Comment by yoe** [comment]
This was actually a bug in the cut script. It was supposed to turn the audio from the left side into a mono audio stream, but that never happened :-)

The bug has now been fixed, so if the talk is re-cut, it should be fine. I've just set the talk back to the `files_found` state, so it should be available for a new review cycle soon. If the audio is now almost unavailable, that would mean the "Alternate channel" option in the "common fixes" area is set incorrectly. In that case, please fix that and ask for a re-cut; the next cut should have the correct audio.

Closing, since this isn't really an issue with SReview as such, but more with one video in one instance of it ;-)

**Comment by kasbah** [comment]
Thanks! I just realised the video is a bit out of sync as well, could you reset to `files_found` again please?

It might make sense to re-open this or open another issue addressing how to re-review a video that has already been approved without involving you. :)
