### ISSUE TITLE
Prettier user interface

### ISSUE THREAD

**Issue by kasbah** [yoe/sreview#34]
I got a little bit curious about what it would take to make the review interface prettier, not just cosmetics but making the interactions more intuitive. I quickly skimmed [talk.html.ep](https://github.com/yoe/sreview/blob/8dad2d197c97600ecfeec1b127ee21b274ab743e/web/templates/talk.html.ep) but it wasn't immediately obvious what kind of requests need to be sent from the client side. 

I was wondering about the feasibility of being able to help with this without knowing any Perl and being able to use Javascript and HTML alone?

EDIT: I am getting a bit further with understanding it. So only one POST request needs to be sent when the review is made.

**Comment by yoe** [comment]
It's certainly my intention to update the UI. I absolutely realise that it's imperfect right now, but it's the best I could do with my limited understanding of modern web development.

It is my long-term intention to use this project to learn more about things like bootstrap and jquery and perhaps some other things, and make the website part of sreview be prettier and snappier and look better in general. Mojolicious (the perl framework that I use) should make that possible, since it also has support for modern web stuff like WebSockets and JSON and more of that niceness.

Currently, yes, a single POST request is all that's needed. I can easily add more on the backend though, and I'd be happy to work with someone who has a better understanding of how the modern web functions.

It will have to wait until FOSDEM review is finished though -- through babysitting the review system and dealing with issues, I haven't had much sleep in the last few days.

**Comment by kasbah** [comment]
The current UI definitely gets the job done which is the most important thing but making it a bit nicer and easier, especially for non technical users, piqued my interest. 

My experience is with [React](https://facebook.github.io/react/) as I use it on [my site](https://kitnic.it). I am a fan of the [semantic-ui](http://semantic-ui.com) and [material-ui](http://www.material-ui.com) frameworks which both work well together with React.

I don't want to push too hard on any library/framework decisions though as I have a million other things I should probably be doing. I will see if I find some time to make a start on something that makes use of the existing back-end as much as possible.

Hope the rest of the review goes smoothly and that you can catch up on some sleep soon!

**Comment by yoe** [comment]
The SReview review form now uses bootstrap, and I've made a number of (slightly) related UI improvements.

There's probably still room for improvement, but a generic "we need to improve" issue is not generally useful. If you have further suggestions, by all means do suggest; in the absense of that, closing this issue.
