### ISSUE TITLE
preroll and postroll slides artwork

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#6]
To be coordinated with Jonas/aghos

**Comment by yoe** [comment]
I've created a (very basic) SVG file which explains how this should work. Download it from https://review.video.fosdem.org/video/assets/fosdem2017-preroll.svg

**Comment by yoe** [comment]
well, not explains, but demonstrates, really :)

**Comment by yoe** [comment]
There is artwork now (though it was posted in the wrong location ;-), just need to test & integrate it.

**Comment by krokodilerian** [comment]
@yoe , where can I see it, to get it in the proper location?

**Comment by yoe** [comment]
The preroll/postroll SVG files were delivered via FOSDEM/video#77. There were a few minor issues with it though, in that the text elements were not flow regions, so that if I changed the text in the SVG file, everything would be aligned incorrectly. Additionally, the nominal pixel size was 1308 rather than 1280 pixels wide, which was wrong.

I fixed both up; the result can be downloaded via <https://review.video.fosdem.org/video/assets/video_front.svg>. Here are some example renderings of what the output would look like:

* <https://review.video.fosdem.org/video/1/A/personal_cloud-pre.png>: longest subtitle
* <https://review.video.fosdem.org/video/1/U/succes_failure_autonomous_driving-pre.png>: longest main title, has no subtitle,
* <https://review.video.fosdem.org/video/1/H/trusted_service_provider-pre.png>: of talks with subtitle, the talk with longest main title
* longest list of speakers happens to be three talks:
    * <https://review.video.fosdem.org/video/1/A/analogue_sim_discussion-pre.png> (no subtitle)
    * <https://review.video.fosdem.org/video/1/A/pcb_dev_discussion-pre.png> (also no subtitle)
    * <https://review.video.fosdem.org/video/1/A/backup_dr_future_ideas-pre.png> (with subtitle)

@aghos, can whoever did these graphics confirm that they look good as presented? There's still time to fix them up if necessary.

(Note: the last one currently has some encoding issues. I'm going to fix that next)

**Comment by yoe** [comment]
@krokodilerian, see my previous entry :-)

**Comment by krokodilerian** [comment]
@yoe , none of these layouts works for the picture-in-picture for the video, we need something with the logo in the top right corner, and maybe not white.

**Comment by yoe** [comment]
@krokodilerian no no no, this is not for the pic-in-pic, this is for the preroll/postroll slides. They show up before or after the video

**Comment by aghos** [comment]
@yoe they like great!

**Comment by yoe** [comment]
Okay, closing then.
