### ISSUE TITLE
Allow putting in information for other reviewers

### ISSUE THREAD

**Issue by RichiH** [yoe/SReview#65]
As devroom manager, I would like to be able to store, along with my review:

1) Name
2) Considerations, etc
3) dateime

in case I start reviewing something someone else already did, or vice versa.

**Comment by yoe** [comment]
@belenbarrospena and I discussed that option, but we decided against it in the end. I don't recall what the arguments were, however (it's been a while).

Can you clarify what you think that option would add?

**Comment by RichiH** [comment]
I want to avoid edit wars where devroom editors keep moving around start/end time of videos being re-re-re-recut. At the moment, other than the timestamps which you see _after_ changing them, there's no way to tell if a video is autocut or not.

**Comment by yoe** [comment]
The "please review" mail gives you a counter as well as the current sum of corrections, so there is *some* way (but that isn't visible to everyone). I suppose we could display that counter as well as the current offsets on the review page somewhere -- but I'll leave that decision to Belen.

**Comment by belenbarrospena** [comment]
I could be misunderstanding things, but it seems to me that the problem comes from the fact that the review request emails go out to more than one person, and those people do not necessarily are in touch with each other or know what the other is doing. We could design something so that people are more aware of what others are doing, but before we get ourselves into that, there might be an easier solution. For example, sending the review request to the speakers only, instead of the speakers and the devroom coordinators. For talks with more than one speaker, we send it to just one of them. 

If after x amount of time (which you can determine) the video has not been reviewed, then we send a second email to the devroom coordinators. Could that solve the problem?

**Comment by yoe** [comment]
That would introduce delays; you'd be essentially playing lottery with "who is responsive". Many speakers do care about video, but about as many do not. I'd rather avoid that.

An alternative would be to have people register that they want to review their own talks, but that introduces a massive amount of bookkeeping and an extra hurdle for people to avoid reviewing ("I have to register? Meh, I'll let someone else do that").

**Comment by belenbarrospena** [comment]
> That would introduce delays; you'd be essentially playing lottery with "who is responsive". Many speakers do care about video, but about as many do not. I'd rather avoid that.

Indeed.

> An alternative would be to have people register that they want to review their own talks, but that introduces a massive amount of bookkeeping and an extra hurdle for people to avoid reviewing ("I have to register? Meh, I'll let someone else do that").

yes, that's true as well. We could flip it and email devroom coordinators only, since they may be somehow more invested on reviewing the talks. 

I can also try and design something. That way we could assess all options and decide which one is the least bad of them all ;)

**Comment by RichiH** [comment]
I am a speaker and devroom manager and with neither hat would I like to be solely responsible. And you _still_ have others who review everything.

The only reliable way, to me, is to allow basic communcation through sreview. Anyone who is logged in should have the name field autofilled, else it should be optional but existing.

**Comment by belenbarrospena** [comment]
This seems a reasonable suggestion, but implementing it could be quite a bit of work. Therefore, before we get ourselves into this, we should 1) make sure we understand the problem, and 2) validate the solution. In short: before building anything we should do some user research.

@yoe Maybe we need a "research" label for this kind of issues. That way we can keep track of what requires research.

**Comment by yoe** [comment]
One way in which we could do this is to change the "Other Brokenness" textarea. Currently it's only meant to be used to signal "there is something terribly wrong with this video"; we could instead create a checkbox for that purpose, and turn the "other brokenness" textarea into a "log message" thing.

That would allow reviewers to communicate amongst themselves.

Since we don't know who is doing review, it won't have that autofilled. However, what it can have is:

- What corrections the reviewer made
- Whether the reviewer requested that an administrator looked at it
- Time and date of the request

The most X recent log message should then be shown on the review interface, possibly behind something that can be scrolled or with a "more..." button that shows the extra messages if/when applicable.

**Comment by RichiH** [comment]
I like the idea of timestamping and including all changes; an audit log of the file so to speak.

Splitting up the orthogonal information of "broken" and "message" is good practice either way. Just please also make sure there's an extra field I can put my name in.

Unless it's deemed to become a problem in practice, I would default to showing full history of all activities. You could even have logs for when things were uploaded initially, etc. I.e. full lifecycle log of the piece of data.

**Comment by yoe** [comment]
@belenbarrospena do you think that adding a checkbox or similar around the "other brokenness" thing to signal "an admin should look at this before we move on" is a good idea? If so, can you suggest what it should look like?

**Comment by belenbarrospena** [comment]
> @belenbarrospena do you think that adding a checkbox or similar around the "other brokenness" thing to signal "an admin should look at this before we move on" is a good idea? If so, can you suggest what it should look like?

Is this related to the video history? Or is this about making sure the "other brokenness" textarea is only used for problems that require admin intervention? I do have an idea for the latter, but not for the video history, which is a much bigger piece. 

The solution I had in mind involves hiding the "other brokenness" text area, and show it only when people selects a checkbox indicating they need help from the video team (see attached image). By turning this into a 2-step process (requires more effort), and removing the temptation of using the textarea just in front of you to say "hi" to the video team, we may go some way towards fixing the problem. 

If you think this could work, let me know I can quickly add it to the UI. 

![Screen Shot 2019-06-06 at 13 52 27](https://user-images.githubusercontent.com/684113/59034386-d8fad300-8862-11e9-99de-ab344ca924c9.png)

**Comment by belenbarrospena** [comment]
Now that I re-read this, I think you are talking about something completely different.

I've opened a separate issue (#72) for the small change to the other brokenness section.

**Comment by yoe** [comment]
@belenbarrospena I implemented this, because I'm going to need something along these lines for DebConf. That doesn't mean I think it looks good, or that there is no room for improvement ;-)

If you have time, let me know and we can look at making this look good, beyond making it functional. Meanwhile, I think this is kinda sorta okay (but there's definitely room for improvement).

Thanks,
