### ISSUE TITLE
(Potential) Unnecessary 'review video' emails triggered

### ISSUE THREAD

**Issue by ei8fdb** [yoe/SReview#74]
I was one of the devroom managers for the Open Source Design (OSD) devroom at this year's FOSDEM.

NB: I've marked this as "potential" as I acknowledge it may be difficult to provide 100% certainty it is an issue.

I'm aware there's a lot that could have happened in between these below steps, but I thought it odd that it had happened on 2 separate occasions when the videos had been reviewed *very* quickly after the talk was given.

# (Potential) problem
When a talk video has been reviewed, and subsequently released the system sends (triggers to send?) "video is now available for you to review" emails.

Below I give 2 examples and sequence of events of where this has occurred.

# Behaviour
In short: 
- the talk happens
- the "please review" email is triggered
- the video is reviewed
- the "video is released" email is triggered
- subsequent "please review" emails are received
- subsequent "video is released" emails are received

Below are detailed sequence of events where this happened.

Example 1: [UXBOX, the time for an open source online prototyping platform has arrived
Vision and short demo](https://fosdem.org/2020/schedule/event/uxbox_open_source_online_prototyping_platform/)
<details><summary>Sequence of events</summary>
<p>

0. Talk happens at 02/02/2020, 13:00 UTC +1
1. 1st Video "is now available for you to review at" email received 13:42:57 UTC +1
2. In between these events, the speaker reviews the video.
3. 1st  Video "has been fully transcoded and uploaded.." received 17:51:42 UTC +1
4. *2nd* Video "is now available for you to review at" email received 15:16 UTC +1
5. Speaker send me an email "Again? I already went through this process"
6. I reply Sat, 15 Feb 2020.
7. *3rd* Video "is now available for you to review at" email 15/02/2020, 20:00 UTC +1
8. Speaker emails me "I went through this a while back and the video went live. I'm unsure why this again", 15/02/2020, 20:35 UTC +1
9. I go back and review video again. 
10. *2nd* Video "has been fully transcoded and uploaded" email received 15/02/2020, 22:01 UTC +1
</p>
</details>

The other example is slightly shorter:

Example 2: [
Some Excerpts from the Theory of Design in Architecture
](https://fosdem.org/2020/schedule/event/some_excerpts_from_theory_of_design_in_architecture/)

<details><summary>Sequence of events</summary>
<p> 

0. Talk takes place 02/02/2020, 11:00 UTC +1
1. 1st Video "is now available for you to review" email received 02/02/2020, 11:42 UTC +1
2. 1st Video "has been fully transcoded and uploaded" email received 03/02/2020, 16:33 UTC +0
3. *2nd* Video "is now available for you to review" email received 17/02/2020, 11:54
</p>
</details>

# Expected behaviour
Once the video was reviewed, no subsequent "video is now available for you to review" emails were received.

**Comment by yoe** [comment]
So, the *actual* behavior should have been:

- The talk happens
- The video is cut based on the schedule, which is almost certainly wrong (because most talks are a bit shorter than scheduled, and there are also clock sync issues)
- The "please review" email is triggered
- The video is reviewed by a human being who sets the correct start and end times and submits it
- The video is cut for a second time
- The "please review" email is triggered for a second time
- The video is reviewed for a second time by a human being, who now confirms that all is well, and allows the video to be released
- The video is transcoded and released
- The announcement email is sent

However, in 133 cases, that process was misunderstood by the reviewer, who released it without actually reviewing the video properly, resulting in a suboptimal video.

133 is a bit much for me to go over all of them in detail, so it's certainly possible that there are some false positives; but the reason the email was triggered was because I went into the database and caused them to be resent, not because of a bug ;-)
