### ISSUE TITLE
dimensioning/navigating (storage) limitations/sync to video.fosdem.org

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#8]
Even the biggest scaleway bare metal has too little storage space to store copies of all reviewed videos.

This will need planning disk/directory layout and a way to sync to video.fosdem.org efficiently.

Upload to v.f.o to be coordinated with Gerry...

**Comment by yoe** [comment]
I already have a perfectly good solution to this problem. Gridengine can keep track of certain resources, disk space being one of them. I can make it so that once a file is transcoded, we upload them and then remove them from the transcoding server. Then gridengine can be told not to start a new transcode unless there's enough disk space.

Keeping this open because that hasn't been implemented yet, but U know how to deal with it.

**Comment by yoe** [comment]
I've created complex configuration[1] to allow for tracking available diskspace on five NFS-mounted filesystems (one per building) as well as /tmp storage (per encode host). This should allow for registering disk space needs for a talk by telling gridengine that a job requires "(time in seconds) x (bytes per second)" bytes of diskspace.

In order for me to make those calculations, though, I'll need to know what the target bandwidth is we're using on our recordings. @markvdb?

[1] "complex" is not to say that it's complicated -- it's just a gridengine term.

**Comment by markvdb** [comment]
5 Mbit max per video box source stream, 2 Mbit per pip stream.

https://github.com/FOSDEM/video/blob/master/software/ansible/playbooks/roles/videobox/templates/video-streamer/video-streamer.sh#L14

https://github.com/FOSDEM/video/blob/master/software/ansible/playbooks/roles/voctop/files/scripts/sink-output.sh#L15

**Comment by yoe** [comment]
I didn't close it, dammit

**Comment by yoe** [comment]
this is now done with the above commit and some changes to the configuration file

**Comment by yoe** [comment]
we'll also need to put different buildings on different volumes. For that, I'll need to spawn C2L machines the day before the event (but that can be dealt with).
